#!/bin/bash

list_files()
{
	tmp=`tempfile`
	unzip -l $1 > $tmp
	rm $2 &> /dev/null

	cat $tmp |
	while read dummy1 dummy2 dummy3 fname; do
		ext=${fname##*.}
		ext=`echo $ext | tr A-Z a-z`

		if [ "$ext" = "scl" ] || [ "$ext" = "trd" ] || [ "$ext" = "z80" ] || [ "$ext" = "p" ] ; then
			echo $fname >> $2
		fi
	done

	rm $tmp
}

extract_files()
{
	unzip -j $1 $2 -d $3 &> /dev/null
}

# arc/zip list <zip file> <result file>
# arc/zip extract <zip file> <file to extract> <result folder>

case "$1" in
	list)
		list_files $2 $3
		;;
	extract)
		extract_files $2 $3 $4
		;;
esac
