#!/bin/bash

list_files() {
    [ -e "$2" ] && rm "$2" &> /dev/null

    unzip -l "$1" | while read dummy1 dummy2 dummy3 fname ; do
        ext=`echo ${fname##*.} | tr A-Z a-z`

        if [ "$ext" = "scl" ] || [ "$ext" = "trd" ] || [ "$ext" = "z80" ] || [ "$ext" = "p" ] || [ "$ext" = "tap" ] ; then
            echo $fname >> $2
        fi
    done
}

extract_files() {
    unzip -o -j "$1" "$2" -d "$3" &> /dev/null
}

# arc/zip list <zip file> <result file>
# arc/zip extract <zip file> <file to extract> <result folder>

case "$1" in
    list)
        list_files "$2" "$3"
        ;;

    extract)
        extract_files "$2" "$3" "$4"
        ;;
esac
