#ifndef PLATFORM__HARDWARE_KEYCODE_H__INCLUDED
#define PLATFORM__HARDWARE_KEYCODE_H__INCLUDED

#include "ZEmuConfig.h"

#ifdef USE_SDL1
    #include <SDL_keysym.h>
#else
    #include <SDL_keycode.h>
#endif

#define HW_KEYCODE_ESCAPE SDLK_ESCAPE
#define HW_KEYCODE_F1 SDLK_F1
#define HW_KEYCODE_F2 SDLK_F2
#define HW_KEYCODE_F3 SDLK_F3
#define HW_KEYCODE_F4 SDLK_F4
#define HW_KEYCODE_F5 SDLK_F5
#define HW_KEYCODE_F6 SDLK_F6
#define HW_KEYCODE_F7 SDLK_F7
#define HW_KEYCODE_F8 SDLK_F8
#define HW_KEYCODE_F9 SDLK_F9
#define HW_KEYCODE_F10 SDLK_F10
#define HW_KEYCODE_F11 SDLK_F11
#define HW_KEYCODE_F12 SDLK_F12
#define HW_KEYCODE_PAUSE SDLK_PAUSE
#define HW_KEYCODE_INSERT SDLK_INSERT
#define HW_KEYCODE_HOME SDLK_HOME
#define HW_KEYCODE_DELETE SDLK_DELETE
#define HW_KEYCODE_END SDLK_END
#define HW_KEYCODE_PAGEUP SDLK_PAGEUP
#define HW_KEYCODE_PAGEDOWN SDLK_PAGEDOWN
#define HW_KEYCODE_1 SDLK_1
#define HW_KEYCODE_2 SDLK_2
#define HW_KEYCODE_3 SDLK_3
#define HW_KEYCODE_4 SDLK_4
#define HW_KEYCODE_5 SDLK_5
#define HW_KEYCODE_6 SDLK_6
#define HW_KEYCODE_7 SDLK_7
#define HW_KEYCODE_8 SDLK_8
#define HW_KEYCODE_9 SDLK_9
#define HW_KEYCODE_0 SDLK_0
#define HW_KEYCODE_BACKSPACE SDLK_BACKSPACE
#define HW_KEYCODE_TAB SDLK_TAB
#define HW_KEYCODE_q SDLK_q
#define HW_KEYCODE_w SDLK_w
#define HW_KEYCODE_e SDLK_e
#define HW_KEYCODE_r SDLK_r
#define HW_KEYCODE_t SDLK_t
#define HW_KEYCODE_y SDLK_y
#define HW_KEYCODE_u SDLK_u
#define HW_KEYCODE_i SDLK_i
#define HW_KEYCODE_o SDLK_o
#define HW_KEYCODE_p SDLK_p
#define HW_KEYCODE_RETURN SDLK_RETURN
#define HW_KEYCODE_CAPSLOCK SDLK_CAPSLOCK
#define HW_KEYCODE_a SDLK_a
#define HW_KEYCODE_s SDLK_s
#define HW_KEYCODE_d SDLK_d
#define HW_KEYCODE_f SDLK_f
#define HW_KEYCODE_g SDLK_g
#define HW_KEYCODE_h SDLK_h
#define HW_KEYCODE_j SDLK_j
#define HW_KEYCODE_k SDLK_k
#define HW_KEYCODE_l SDLK_l
#define HW_KEYCODE_LSHIFT SDLK_LSHIFT
#define HW_KEYCODE_z SDLK_z
#define HW_KEYCODE_x SDLK_x
#define HW_KEYCODE_c SDLK_c
#define HW_KEYCODE_v SDLK_v
#define HW_KEYCODE_b SDLK_b
#define HW_KEYCODE_n SDLK_n
#define HW_KEYCODE_m SDLK_m
#define HW_KEYCODE_RSHIFT SDLK_RSHIFT
#define HW_KEYCODE_LCTRL SDLK_LCTRL
#define HW_KEYCODE_LALT SDLK_LALT
#define HW_KEYCODE_SPACE SDLK_SPACE
#define HW_KEYCODE_RALT SDLK_RALT
#define HW_KEYCODE_RCTRL SDLK_RCTRL
#define HW_KEYCODE_UP SDLK_UP
#define HW_KEYCODE_DOWN SDLK_DOWN
#define HW_KEYCODE_LEFT SDLK_LEFT
#define HW_KEYCODE_RIGHT SDLK_RIGHT

#ifdef USE_SDL1
    #define HW_KEYCODE_LSUPER SDLK_LSUPER
    #define HW_KEYCODE_RSUPER SDLK_RSUPER
    #define HW_KEYCODE_NUMLOCK SDLK_NUMLOCK
#else
    #define HW_KEYCODE_LSUPER SDLK_LGUI
    #define HW_KEYCODE_RSUPER SDLK_RGUI
    #define HW_KEYCODE_NUMLOCK SDLK_NUMLOCKCLEAR
#endif

#endif
